### ISSUE TITLE
Set region for aws client

### ISSUE THREAD

**Issue by jmatusewicz** [bringmeister/aws-kinesis-spring-boot-starter#59]
After updating aws kinesis client dependency from 1.8.10 to 1.9.3 (e9db9757c055eb1c9e20d0f74dc4255ce90b50c5) following warnings are logged during application start:

```
| WARN | No configuration received for endpoint and region, will default region to us-east-1
| WARN | Received configuration for endpoint as https://dynamodb.eu-central-1.amazonaws.com, and region as null.
| WARN | Received configuration for endpoint as https://kinesis.eu-central-1.amazonaws.com, and region
```
Cloud Watch client is affected by not setting the region.

Looks like the the region has to be set here: https://github.com/bringmeister/aws-kinesis-spring-boot-starter/blob/master/src/main/kotlin/de/bringmeister/spring/aws/kinesis/KinesisClientProvider.kt#L36

**Comment by jrehwaldt** [comment]
From watching the Amazon SDK source code I believe this is a misplaced warning log statement and there is actually nothing to warn. Didn't watch too much into it, though.

**Comment by tuhrig** [comment]
Fixed by https://github.com/bringmeister/aws-kinesis-spring-boot-starter/releases/tag/0.2.5.
