### ISSUE TITLE
Unable to handle messages in java without jackson-module-kotlin dependency

### ISSUE THREAD

**Issue by phazebroek** [bringmeister/aws-kinesis-spring-boot-starter#84]
In a java project, without the jackson-module-kotlin dependency we get the following error:

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `de.bringmeister.spring.aws.kinesis.Record` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

Expected that this dependency would be part of the aws-kinesis-spring-boot-starter dependency.

**Comment by jrehwaldt** [comment]
Thanks for the report.
